import type { ShopifyProduct } from "@/lib/hooks/useProducts";

const img = (file: string, alt: string) => ({
  id: file,
  src: `/images/catalog/${file}.jpg`,
  altText: alt,
});

/**
 * CATÁLOGO COMERCIAL FBG, JUNHO 2026
 * Todas as referências oficiais do catálogo Freebong Jeans.
 * Fotos extraídas do catálogo oficial (uma pasta /public/images/catalog).
 */
export const MOCK_PRODUCTS: ShopifyProduct[] = [
  {
    id: "calca-stratus-ca-059-01",
    title: "Calça Stratus (CA 059-01)",
    handle: "calca-stratus-ca-059-01",
    description: "Uma proposta mais larga do jeans FBG, trazendo um visual despojado sem perder o conforto. Referência: CA 059-01. Composição: 100% Algodão. Disponibilidade: Programação.",
    descriptionHtml: "<p>Uma proposta mais larga do jeans FBG, trazendo um visual despojado sem perder o conforto.</p><p><strong>Referência:</strong> CA 059-01<br/><strong>Composição:</strong> 100% Algodão<br/><strong>Disponibilidade:</strong> Programação</p>",
    productType: "Calça Jeans",
    tags: ["calca", "wide", "programacao", "ca-059-01"],
    images: [
      img("p06_02", "Calça Stratus (CA 059-01), frente"),
      img("p06_03", "Calça Stratus (CA 059-01), detalhe"),
      img("p06_04", "Calça Stratus (CA 059-01), costas"),
    ],
    variants: [
      { id: "calca-stratus-ca-059-01-38", title: "38", price: "279.99", available: true, image: null },
      { id: "calca-stratus-ca-059-01-40", title: "40", price: "279.99", available: true, image: null },
      { id: "calca-stratus-ca-059-01-42", title: "42", price: "279.99", available: true, image: null },
      { id: "calca-stratus-ca-059-01-44", title: "44", price: "279.99", available: true, image: null },
      { id: "calca-stratus-ca-059-01-46", title: "46", price: "279.99", available: true, image: null },
      { id: "calca-stratus-ca-059-01-48", title: "48", price: "279.99", available: true, image: null },
    ],
  },
  {
    id: "calca-stratus-ca-059-02",
    title: "Calça Stratus (CA 059-02)",
    handle: "calca-stratus-ca-059-02",
    description: "Uma proposta mais larga do jeans FBG, trazendo um visual despojado sem perder o conforto. Referência: CA 059-02. Composição: 100% Algodão. Disponibilidade: Programação.",
    descriptionHtml: "<p>Uma proposta mais larga do jeans FBG, trazendo um visual despojado sem perder o conforto.</p><p><strong>Referência:</strong> CA 059-02<br/><strong>Composição:</strong> 100% Algodão<br/><strong>Disponibilidade:</strong> Programação</p>",
    productType: "Calça Jeans",
    tags: ["calca", "wide", "programacao", "ca-059-02"],
    images: [
      img("p06_05", "Calça Stratus (CA 059-02), frente"),
      img("p06_06", "Calça Stratus (CA 059-02), detalhe"),
      img("p06_07", "Calça Stratus (CA 059-02), costas"),
    ],
    variants: [
      { id: "calca-stratus-ca-059-02-38", title: "38", price: "279.99", available: true, image: null },
      { id: "calca-stratus-ca-059-02-40", title: "40", price: "279.99", available: true, image: null },
      { id: "calca-stratus-ca-059-02-42", title: "42", price: "279.99", available: true, image: null },
      { id: "calca-stratus-ca-059-02-44", title: "44", price: "279.99", available: true, image: null },
      { id: "calca-stratus-ca-059-02-46", title: "46", price: "279.99", available: true, image: null },
      { id: "calca-stratus-ca-059-02-48", title: "48", price: "279.99", available: true, image: null },
    ],
  },
  {
    id: "calca-skinny-legacy-ca-053-02",
    title: "Calça Skinny Legacy (CA 053-02)",
    handle: "calca-skinny-legacy-ca-053-02",
    description: "A calça Legacy é a definição de versatilidade com estilo. Com uma lavagem suave e moderna, ela entrega um visual clean que se adapta a qualquer ocasião, do casual ao urbano. Referência: CA 053-02. Composição: 99% Algodão · 1% Elastano. Disponibilidade: Pronta Entrega.",
    descriptionHtml: "<p>A calça Legacy é a definição de versatilidade com estilo. Com uma lavagem suave e moderna, ela entrega um visual clean que se adapta a qualquer ocasião, do casual ao urbano.</p><p><strong>Referência:</strong> CA 053-02<br/><strong>Composição:</strong> 99% Algodão · 1% Elastano<br/><strong>Disponibilidade:</strong> Pronta Entrega</p>",
    productType: "Calça Jeans",
    tags: ["calca", "skinny", "pronta-entrega", "ca-053-02"],
    images: [
      img("p07_02", "Calça Skinny Legacy (CA 053-02), frente"),
      img("p07_03", "Calça Skinny Legacy (CA 053-02), detalhe"),
      img("p07_04", "Calça Skinny Legacy (CA 053-02), costas"),
    ],
    variants: [
      { id: "calca-skinny-legacy-ca-053-02-38", title: "38", price: "279.99", available: true, image: null },
      { id: "calca-skinny-legacy-ca-053-02-40", title: "40", price: "279.99", available: true, image: null },
      { id: "calca-skinny-legacy-ca-053-02-42", title: "42", price: "279.99", available: true, image: null },
      { id: "calca-skinny-legacy-ca-053-02-44", title: "44", price: "279.99", available: true, image: null },
      { id: "calca-skinny-legacy-ca-053-02-46", title: "46", price: "279.99", available: true, image: null },
      { id: "calca-skinny-legacy-ca-053-02-48", title: "48", price: "279.99", available: true, image: null },
    ],
  },
  {
    id: "calca-skinny-legacy-ca-053-03",
    title: "Calça Skinny Legacy (CA 053-03)",
    handle: "calca-skinny-legacy-ca-053-03",
    description: "A calça Legacy é a definição de versatilidade com estilo. Com uma lavagem suave e moderna, ela entrega um visual clean que se adapta a qualquer ocasião, do casual ao urbano. Referência: CA 053-03. Composição: 99% Algodão · 1% Elastano. Disponibilidade: Pronta Entrega.",
    descriptionHtml: "<p>A calça Legacy é a definição de versatilidade com estilo. Com uma lavagem suave e moderna, ela entrega um visual clean que se adapta a qualquer ocasião, do casual ao urbano.</p><p><strong>Referência:</strong> CA 053-03<br/><strong>Composição:</strong> 99% Algodão · 1% Elastano<br/><strong>Disponibilidade:</strong> Pronta Entrega</p>",
    productType: "Calça Jeans",
    tags: ["calca", "skinny", "pronta-entrega", "ca-053-03"],
    images: [
      img("p07_05", "Calça Skinny Legacy (CA 053-03), frente"),
      img("p07_06", "Calça Skinny Legacy (CA 053-03), detalhe"),
      img("p07_07", "Calça Skinny Legacy (CA 053-03), costas"),
    ],
    variants: [
      { id: "calca-skinny-legacy-ca-053-03-38", title: "38", price: "279.99", available: true, image: null },
      { id: "calca-skinny-legacy-ca-053-03-40", title: "40", price: "279.99", available: true, image: null },
      { id: "calca-skinny-legacy-ca-053-03-42", title: "42", price: "279.99", available: true, image: null },
      { id: "calca-skinny-legacy-ca-053-03-44", title: "44", price: "279.99", available: true, image: null },
      { id: "calca-skinny-legacy-ca-053-03-46", title: "46", price: "279.99", available: true, image: null },
      { id: "calca-skinny-legacy-ca-053-03-48", title: "48", price: "279.99", available: true, image: null },
    ],
  },
  {
    id: "calca-legacy-95-ca-053-01",
    title: "Calça Legacy 95",
    handle: "calca-legacy-95-ca-053-01",
    description: "A calça Legacy é a definição de versatilidade com estilo. Com uma lavagem suave e moderna, ela entrega um visual clean que se adapta a qualquer ocasião, do casual ao urbano. Referência: CA 053-01. Composição: 99% Algodão · 1% Elastano. Disponibilidade: Pronta Entrega.",
    descriptionHtml: "<p>A calça Legacy é a definição de versatilidade com estilo. Com uma lavagem suave e moderna, ela entrega um visual clean que se adapta a qualquer ocasião, do casual ao urbano.</p><p><strong>Referência:</strong> CA 053-01<br/><strong>Composição:</strong> 99% Algodão · 1% Elastano<br/><strong>Disponibilidade:</strong> Pronta Entrega</p>",
    productType: "Calça Jeans",
    tags: ["calca", "skinny", "pronta-entrega", "ca-053-01"],
    images: [
      img("p08_02", "Calça Legacy 95, frente"),
      img("p08_03", "Calça Legacy 95, detalhe"),
      img("p08_04", "Calça Legacy 95, costas"),
    ],
    variants: [
      { id: "calca-legacy-95-ca-053-01-38", title: "38", price: "279.99", available: true, image: null },
      { id: "calca-legacy-95-ca-053-01-40", title: "40", price: "279.99", available: true, image: null },
      { id: "calca-legacy-95-ca-053-01-42", title: "42", price: "279.99", available: true, image: null },
      { id: "calca-legacy-95-ca-053-01-44", title: "44", price: "279.99", available: true, image: null },
      { id: "calca-legacy-95-ca-053-01-46", title: "46", price: "279.99", available: true, image: null },
      { id: "calca-legacy-95-ca-053-01-48", title: "48", price: "279.99", available: true, image: null },
    ],
  },
  {
    id: "calca-legacy-galaxy-ca-062-01",
    title: "Calça Legacy Galaxy (CA 062-01)",
    handle: "calca-legacy-galaxy-ca-062-01",
    description: "Calça masculina com tingimento azul intenso, desenvolvida para valorizar contrastes e lavagens marcantes. Referência: CA 062-01. Composição: 99% Algodão · 1% Elastano. Disponibilidade: Pronta Entrega.",
    descriptionHtml: "<p>Calça masculina com tingimento azul intenso, desenvolvida para valorizar contrastes e lavagens marcantes.</p><p><strong>Referência:</strong> CA 062-01<br/><strong>Composição:</strong> 99% Algodão · 1% Elastano<br/><strong>Disponibilidade:</strong> Pronta Entrega</p>",
    productType: "Calça Jeans",
    tags: ["calca", "skinny", "pronta-entrega", "ca-062-01"],
    images: [
      img("p08_05", "Calça Legacy Galaxy (CA 062-01), frente"),
      img("p08_06", "Calça Legacy Galaxy (CA 062-01), detalhe"),
      img("p08_07", "Calça Legacy Galaxy (CA 062-01), costas"),
    ],
    variants: [
      { id: "calca-legacy-galaxy-ca-062-01-38", title: "38", price: "279.99", available: true, image: null },
      { id: "calca-legacy-galaxy-ca-062-01-40", title: "40", price: "279.99", available: true, image: null },
      { id: "calca-legacy-galaxy-ca-062-01-42", title: "42", price: "279.99", available: true, image: null },
      { id: "calca-legacy-galaxy-ca-062-01-44", title: "44", price: "279.99", available: true, image: null },
      { id: "calca-legacy-galaxy-ca-062-01-46", title: "46", price: "279.99", available: true, image: null },
      { id: "calca-legacy-galaxy-ca-062-01-48", title: "48", price: "279.99", available: true, image: null },
    ],
  },
  {
    id: "calca-skinny-up-black-ca-061-02",
    title: "Calça Skinny Up Black (CA 061-02)",
    handle: "calca-skinny-up-black-ca-061-02",
    description: "Calça masculina desenvolvida em denim black de alta intensidade, com base predominante em algodão que preserva a autenticidade do jeans e elasticidade que garante conforto no uso. Referência: CA 061-02. Composição: 99% Algodão · 1% Elastano. Disponibilidade: Pronta Entrega.",
    descriptionHtml: "<p>Calça masculina desenvolvida em denim black de alta intensidade, com base predominante em algodão que preserva a autenticidade do jeans e elasticidade que garante conforto no uso.</p><p><strong>Referência:</strong> CA 061-02<br/><strong>Composição:</strong> 99% Algodão · 1% Elastano<br/><strong>Disponibilidade:</strong> Pronta Entrega</p>",
    productType: "Calça Jeans",
    tags: ["calca", "skinny", "pronta-entrega", "ca-061-02"],
    images: [
      img("p09_02", "Calça Skinny Up Black (CA 061-02), frente"),
      img("p09_04", "Calça Skinny Up Black (CA 061-02), detalhe"),
      img("p09_03", "Calça Skinny Up Black (CA 061-02), costas"),
    ],
    variants: [
      { id: "calca-skinny-up-black-ca-061-02-38", title: "38", price: "279.99", available: true, image: null },
      { id: "calca-skinny-up-black-ca-061-02-40", title: "40", price: "279.99", available: true, image: null },
      { id: "calca-skinny-up-black-ca-061-02-42", title: "42", price: "279.99", available: true, image: null },
      { id: "calca-skinny-up-black-ca-061-02-44", title: "44", price: "279.99", available: true, image: null },
      { id: "calca-skinny-up-black-ca-061-02-46", title: "46", price: "279.99", available: true, image: null },
      { id: "calca-skinny-up-black-ca-061-02-48", title: "48", price: "279.99", available: true, image: null },
    ],
  },
  {
    id: "calca-skinny-up-black-ca-061-01",
    title: "Calça Skinny Up Black (CA 061-01)",
    handle: "calca-skinny-up-black-ca-061-01",
    description: "Calça masculina desenvolvida em denim black de alta intensidade, com base predominante em algodão que preserva a autenticidade do jeans e elasticidade que garante conforto no uso. Referência: CA 061-01. Composição: 99% Algodão · 1% Elastano. Disponibilidade: Pronta Entrega.",
    descriptionHtml: "<p>Calça masculina desenvolvida em denim black de alta intensidade, com base predominante em algodão que preserva a autenticidade do jeans e elasticidade que garante conforto no uso.</p><p><strong>Referência:</strong> CA 061-01<br/><strong>Composição:</strong> 99% Algodão · 1% Elastano<br/><strong>Disponibilidade:</strong> Pronta Entrega</p>",
    productType: "Calça Jeans",
    tags: ["calca", "skinny", "pronta-entrega", "ca-061-01"],
    images: [
      img("p09_05", "Calça Skinny Up Black (CA 061-01), frente"),
      img("p09_06", "Calça Skinny Up Black (CA 061-01), detalhe"),
      img("p09_07", "Calça Skinny Up Black (CA 061-01), costas"),
    ],
    variants: [
      { id: "calca-skinny-up-black-ca-061-01-38", title: "38", price: "279.99", available: true, image: null },
      { id: "calca-skinny-up-black-ca-061-01-40", title: "40", price: "279.99", available: true, image: null },
      { id: "calca-skinny-up-black-ca-061-01-42", title: "42", price: "279.99", available: true, image: null },
      { id: "calca-skinny-up-black-ca-061-01-44", title: "44", price: "279.99", available: true, image: null },
      { id: "calca-skinny-up-black-ca-061-01-46", title: "46", price: "279.99", available: true, image: null },
      { id: "calca-skinny-up-black-ca-061-01-48", title: "48", price: "279.99", available: true, image: null },
    ],
  },
  {
    id: "calca-skinny-west-plus-ca-057-01",
    title: "Calça Skinny West Plus",
    handle: "calca-skinny-west-plus-ca-057-01",
    description: "Calça skinny West Plus em denim com elastano. Caimento ajustado ao corpo, lavagem escura e conforto para o dia a dia. Referência: CA 057-01. Composição: 99% Algodão · 1% Elastano. Disponibilidade: Pronta Entrega.",
    descriptionHtml: "<p>Calça skinny West Plus em denim com elastano. Caimento ajustado ao corpo, lavagem escura e conforto para o dia a dia.</p><p><strong>Referência:</strong> CA 057-01<br/><strong>Composição:</strong> 99% Algodão · 1% Elastano<br/><strong>Disponibilidade:</strong> Pronta Entrega</p>",
    productType: "Calça Jeans",
    tags: ["calca", "skinny", "pronta-entrega", "ca-057-01"],
    images: [
      img("p10_01", "Calça Skinny West Plus, frente"),
      img("p10_02", "Calça Skinny West Plus, detalhe"),
      img("p10_03", "Calça Skinny West Plus, costas"),
    ],
    variants: [
      { id: "calca-skinny-west-plus-ca-057-01-38", title: "38", price: "279.99", available: true, image: null },
      { id: "calca-skinny-west-plus-ca-057-01-40", title: "40", price: "279.99", available: true, image: null },
      { id: "calca-skinny-west-plus-ca-057-01-42", title: "42", price: "279.99", available: true, image: null },
      { id: "calca-skinny-west-plus-ca-057-01-44", title: "44", price: "279.99", available: true, image: null },
      { id: "calca-skinny-west-plus-ca-057-01-46", title: "46", price: "279.99", available: true, image: null },
      { id: "calca-skinny-west-plus-ca-057-01-48", title: "48", price: "279.99", available: true, image: null },
    ],
  },
  {
    id: "calca-legacy-galaxy-alto-stretch-ca-062",
    title: "Calça Legacy Galaxy Alto Stretch (CA 062)",
    handle: "calca-legacy-galaxy-alto-stretch-ca-062",
    description: "Alto stretch com estrutura. Com 42% de elasticidade, o artigo proporciona conforto superior sem perder o aspecto visual do jeans. Referência: CA 062. Composição: 99% Algodão · 1% Elastano. Disponibilidade: Pronta Entrega.",
    descriptionHtml: "<p>Alto stretch com estrutura. Com 42% de elasticidade, o artigo proporciona conforto superior sem perder o aspecto visual do jeans.</p><p><strong>Referência:</strong> CA 062<br/><strong>Composição:</strong> 99% Algodão · 1% Elastano<br/><strong>Disponibilidade:</strong> Pronta Entrega</p>",
    productType: "Calça Jeans",
    tags: ["calca", "skinny", "pronta-entrega", "ca-062"],
    images: [
      img("p10_04", "Calça Legacy Galaxy Alto Stretch (CA 062), frente"),
      img("p10_05", "Calça Legacy Galaxy Alto Stretch (CA 062), detalhe"),
      img("p10_06", "Calça Legacy Galaxy Alto Stretch (CA 062), costas"),
    ],
    variants: [
      { id: "calca-legacy-galaxy-alto-stretch-ca-062-38", title: "38", price: "279.99", available: true, image: null },
      { id: "calca-legacy-galaxy-alto-stretch-ca-062-40", title: "40", price: "279.99", available: true, image: null },
      { id: "calca-legacy-galaxy-alto-stretch-ca-062-42", title: "42", price: "279.99", available: true, image: null },
      { id: "calca-legacy-galaxy-alto-stretch-ca-062-44", title: "44", price: "279.99", available: true, image: null },
      { id: "calca-legacy-galaxy-alto-stretch-ca-062-46", title: "46", price: "279.99", available: true, image: null },
      { id: "calca-legacy-galaxy-alto-stretch-ca-062-48", title: "48", price: "279.99", available: true, image: null },
    ],
  },
  {
    id: "calca-skinny-up-black-ca-052-02",
    title: "Calça Skinny Up Black (CA 052-02)",
    handle: "calca-skinny-up-black-ca-052-02",
    description: "Calça masculina desenvolvida em denim black de alta intensidade, com base predominante em algodão que preserva a autenticidade do jeans e elasticidade que garante conforto no uso. Referência: CA 052-02. Composição: 99% Algodão · 1% Elastano. Disponibilidade: Pronta Entrega.",
    descriptionHtml: "<p>Calça masculina desenvolvida em denim black de alta intensidade, com base predominante em algodão que preserva a autenticidade do jeans e elasticidade que garante conforto no uso.</p><p><strong>Referência:</strong> CA 052-02<br/><strong>Composição:</strong> 99% Algodão · 1% Elastano<br/><strong>Disponibilidade:</strong> Pronta Entrega</p>",
    productType: "Calça Jeans",
    tags: ["calca", "skinny", "pronta-entrega", "ca-052-02"],
    images: [
      img("p11_02", "Calça Skinny Up Black (CA 052-02), frente"),
      img("p11_04", "Calça Skinny Up Black (CA 052-02), detalhe"),
      img("p11_03", "Calça Skinny Up Black (CA 052-02), costas"),
    ],
    variants: [
      { id: "calca-skinny-up-black-ca-052-02-38", title: "38", price: "279.99", available: true, image: null },
      { id: "calca-skinny-up-black-ca-052-02-40", title: "40", price: "279.99", available: true, image: null },
      { id: "calca-skinny-up-black-ca-052-02-42", title: "42", price: "279.99", available: true, image: null },
      { id: "calca-skinny-up-black-ca-052-02-44", title: "44", price: "279.99", available: true, image: null },
      { id: "calca-skinny-up-black-ca-052-02-46", title: "46", price: "279.99", available: true, image: null },
      { id: "calca-skinny-up-black-ca-052-02-48", title: "48", price: "279.99", available: true, image: null },
    ],
  },
  {
    id: "calca-skinny-tec-white-denim-ca-056",
    title: "Calça Skinny Tec-White Denim",
    handle: "calca-skinny-tec-white-denim-ca-056",
    description: "Calça confeccionada em tecido Tec White, que oferece conforto, respirabilidade e fácil manutenção. Alta resistência a manchas e excelente durabilidade, garantindo praticidade e um visual sempre impecável. Referência: CA 056. Composição: 99% Algodão · 1% Elastano. Disponibilidade: Pronta Entrega.",
    descriptionHtml: "<p>Calça confeccionada em tecido Tec White, que oferece conforto, respirabilidade e fácil manutenção. Alta resistência a manchas e excelente durabilidade, garantindo praticidade e um visual sempre impecável.</p><p><strong>Referência:</strong> CA 056<br/><strong>Composição:</strong> 99% Algodão · 1% Elastano<br/><strong>Disponibilidade:</strong> Pronta Entrega</p>",
    productType: "Calça Jeans",
    tags: ["calca", "skinny", "pronta-entrega", "ca-056"],
    images: [
      img("p12_02", "Calça Skinny Tec-White Denim, frente"),
      img("p12_03", "Calça Skinny Tec-White Denim, detalhe"),
      img("p12_04", "Calça Skinny Tec-White Denim, costas"),
    ],
    variants: [
      { id: "calca-skinny-tec-white-denim-ca-056-38", title: "38", price: "279.99", available: true, image: null },
      { id: "calca-skinny-tec-white-denim-ca-056-40", title: "40", price: "279.99", available: true, image: null },
      { id: "calca-skinny-tec-white-denim-ca-056-42", title: "42", price: "279.99", available: true, image: null },
      { id: "calca-skinny-tec-white-denim-ca-056-44", title: "44", price: "279.99", available: true, image: null },
      { id: "calca-skinny-tec-white-denim-ca-056-46", title: "46", price: "279.99", available: true, image: null },
      { id: "calca-skinny-tec-white-denim-ca-056-48", title: "48", price: "279.99", available: true, image: null },
    ],
  },
  {
    id: "calca-skinny-up-black-ca-064-01",
    title: "Calça Skinny Up Black (CA 064-01)",
    handle: "calca-skinny-up-black-ca-064-01",
    description: "Calça masculina desenvolvida em denim black de alta intensidade, com base predominante em algodão que preserva a autenticidade do jeans e elasticidade que garante conforto no uso. Referência: CA 064-01. Composição: 99% Algodão · 1% Elastano. Disponibilidade: Pronta Entrega.",
    descriptionHtml: "<p>Calça masculina desenvolvida em denim black de alta intensidade, com base predominante em algodão que preserva a autenticidade do jeans e elasticidade que garante conforto no uso.</p><p><strong>Referência:</strong> CA 064-01<br/><strong>Composição:</strong> 99% Algodão · 1% Elastano<br/><strong>Disponibilidade:</strong> Pronta Entrega</p>",
    productType: "Calça Jeans",
    tags: ["calca", "skinny", "pronta-entrega", "ca-064-01"],
    images: [
      img("p12_05", "Calça Skinny Up Black (CA 064-01), frente"),
      img("p12_06", "Calça Skinny Up Black (CA 064-01), detalhe"),
      img("p12_07", "Calça Skinny Up Black (CA 064-01), costas"),
    ],
    variants: [
      { id: "calca-skinny-up-black-ca-064-01-38", title: "38", price: "279.99", available: true, image: null },
      { id: "calca-skinny-up-black-ca-064-01-40", title: "40", price: "279.99", available: true, image: null },
      { id: "calca-skinny-up-black-ca-064-01-42", title: "42", price: "279.99", available: true, image: null },
      { id: "calca-skinny-up-black-ca-064-01-44", title: "44", price: "279.99", available: true, image: null },
      { id: "calca-skinny-up-black-ca-064-01-46", title: "46", price: "279.99", available: true, image: null },
      { id: "calca-skinny-up-black-ca-064-01-48", title: "48", price: "279.99", available: true, image: null },
    ],
  },
  {
    id: "calca-skinny-queen-triblend-ca-51002",
    title: "Calça Skinny Queen Triblend (CA 51002)",
    handle: "calca-skinny-queen-triblend-ca-51002",
    description: "Calça skinny confeccionada em tecido Queen Triblend, que combina diferentes fibras para oferecer toque macio, elasticidade e alta durabilidade. Caimento ajustado ao corpo, valorizando a silhueta com conforto e liberdade de movimento. Referência: CA 51002. Composição: 98% Algodão · 2% Elastano. Disponibilidade: Pronta Entrega.",
    descriptionHtml: "<p>Calça skinny confeccionada em tecido Queen Triblend, que combina diferentes fibras para oferecer toque macio, elasticidade e alta durabilidade. Caimento ajustado ao corpo, valorizando a silhueta com conforto e liberdade de movimento.</p><p><strong>Referência:</strong> CA 51002<br/><strong>Composição:</strong> 98% Algodão · 2% Elastano<br/><strong>Disponibilidade:</strong> Pronta Entrega</p>",
    productType: "Calça Jeans",
    tags: ["calca", "skinny", "pronta-entrega", "ca-51002"],
    images: [
      img("p13_03", "Calça Skinny Queen Triblend (CA 51002), frente"),
      img("p13_04", "Calça Skinny Queen Triblend (CA 51002), detalhe"),
      img("p13_05", "Calça Skinny Queen Triblend (CA 51002), costas"),
    ],
    variants: [
      { id: "calca-skinny-queen-triblend-ca-51002-38", title: "38", price: "279.99", available: true, image: null },
      { id: "calca-skinny-queen-triblend-ca-51002-40", title: "40", price: "279.99", available: true, image: null },
      { id: "calca-skinny-queen-triblend-ca-51002-42", title: "42", price: "279.99", available: true, image: null },
      { id: "calca-skinny-queen-triblend-ca-51002-44", title: "44", price: "279.99", available: true, image: null },
      { id: "calca-skinny-queen-triblend-ca-51002-46", title: "46", price: "279.99", available: true, image: null },
      { id: "calca-skinny-queen-triblend-ca-51002-48", title: "48", price: "279.99", available: true, image: null },
    ],
  },
  {
    id: "calca-skinny-queen-triblend-ca-51003",
    title: "Calça Skinny Queen Triblend (CA 51003)",
    handle: "calca-skinny-queen-triblend-ca-51003",
    description: "Calça skinny confeccionada em tecido Queen Triblend, que combina diferentes fibras para oferecer toque macio, elasticidade e alta durabilidade. Caimento ajustado ao corpo, valorizando a silhueta com conforto e liberdade de movimento. Referência: CA 51003. Composição: 98% Algodão · 2% Elastano. Disponibilidade: Pronta Entrega.",
    descriptionHtml: "<p>Calça skinny confeccionada em tecido Queen Triblend, que combina diferentes fibras para oferecer toque macio, elasticidade e alta durabilidade. Caimento ajustado ao corpo, valorizando a silhueta com conforto e liberdade de movimento.</p><p><strong>Referência:</strong> CA 51003<br/><strong>Composição:</strong> 98% Algodão · 2% Elastano<br/><strong>Disponibilidade:</strong> Pronta Entrega</p>",
    productType: "Calça Jeans",
    tags: ["calca", "skinny", "pronta-entrega", "ca-51003"],
    images: [
      img("p13_06", "Calça Skinny Queen Triblend (CA 51003), frente"),
      img("p13_07", "Calça Skinny Queen Triblend (CA 51003), detalhe"),
      img("p13_08", "Calça Skinny Queen Triblend (CA 51003), costas"),
      img("p13_01", "Calça Skinny Queen Triblend (CA 51003), close"),
    ],
    variants: [
      { id: "calca-skinny-queen-triblend-ca-51003-38", title: "38", price: "279.99", available: true, image: null },
      { id: "calca-skinny-queen-triblend-ca-51003-40", title: "40", price: "279.99", available: true, image: null },
      { id: "calca-skinny-queen-triblend-ca-51003-42", title: "42", price: "279.99", available: true, image: null },
      { id: "calca-skinny-queen-triblend-ca-51003-44", title: "44", price: "279.99", available: true, image: null },
      { id: "calca-skinny-queen-triblend-ca-51003-46", title: "46", price: "279.99", available: true, image: null },
      { id: "calca-skinny-queen-triblend-ca-51003-48", title: "48", price: "279.99", available: true, image: null },
    ],
  },
  {
    id: "calca-skinny-new-sandler-ca-060",
    title: "Calça Skinny New Sandler",
    handle: "calca-skinny-new-sandler-ca-060",
    description: "Com 22% de stretch, entrega uma experiência mais natural ao vestir, mantendo a firmeza visual e a estética limpa que valorizam a peça. Lavagem média. Referência: CA 060. Composição: 99% Algodão · 1% Elastano. Disponibilidade: Pronta Entrega.",
    descriptionHtml: "<p>Com 22% de stretch, entrega uma experiência mais natural ao vestir, mantendo a firmeza visual e a estética limpa que valorizam a peça. Lavagem média.</p><p><strong>Referência:</strong> CA 060<br/><strong>Composição:</strong> 99% Algodão · 1% Elastano<br/><strong>Disponibilidade:</strong> Pronta Entrega</p>",
    productType: "Calça Jeans",
    tags: ["calca", "skinny", "pronta-entrega", "ca-060"],
    images: [
      img("p14_02", "Calça Skinny New Sandler, frente"),
      img("p14_03", "Calça Skinny New Sandler, detalhe"),
      img("p14_04", "Calça Skinny New Sandler, costas"),
    ],
    variants: [
      { id: "calca-skinny-new-sandler-ca-060-38", title: "38", price: "279.99", available: true, image: null },
      { id: "calca-skinny-new-sandler-ca-060-40", title: "40", price: "279.99", available: true, image: null },
      { id: "calca-skinny-new-sandler-ca-060-42", title: "42", price: "279.99", available: true, image: null },
      { id: "calca-skinny-new-sandler-ca-060-44", title: "44", price: "279.99", available: true, image: null },
      { id: "calca-skinny-new-sandler-ca-060-46", title: "46", price: "279.99", available: true, image: null },
      { id: "calca-skinny-new-sandler-ca-060-48", title: "48", price: "279.99", available: true, image: null },
    ],
  },
  {
    id: "calca-slim-megaflex-total-ca-52004",
    title: "Calça Slim Megaflex Total (CA 52004)",
    handle: "calca-slim-megaflex-total-ca-52004",
    description: "Calça masculina desenvolvida com tecido Megaflex, que oferece alta elasticidade e conforto superior. Caimento ajustado ao corpo, proporcionando mobilidade e estilo para o dia a dia. Referência: CA 52004. Composição: 68% Algodão · 10% Viscose · 20% Poliéster · 2% Elastano. Disponibilidade: Pronta Entrega.",
    descriptionHtml: "<p>Calça masculina desenvolvida com tecido Megaflex, que oferece alta elasticidade e conforto superior. Caimento ajustado ao corpo, proporcionando mobilidade e estilo para o dia a dia.</p><p><strong>Referência:</strong> CA 52004<br/><strong>Composição:</strong> 68% Algodão · 10% Viscose · 20% Poliéster · 2% Elastano<br/><strong>Disponibilidade:</strong> Pronta Entrega</p>",
    productType: "Calça Jeans",
    tags: ["calca", "slim", "pronta-entrega", "novidade", "ca-52004"],
    images: [
      img("p15_06", "Calça Slim Megaflex Total (CA 52004), frente"),
      img("p15_07", "Calça Slim Megaflex Total (CA 52004), detalhe"),
      img("p15_05", "Calça Slim Megaflex Total (CA 52004), costas"),
    ],
    variants: [
      { id: "calca-slim-megaflex-total-ca-52004-38", title: "38", price: "289.99", available: true, image: null },
      { id: "calca-slim-megaflex-total-ca-52004-40", title: "40", price: "289.99", available: true, image: null },
      { id: "calca-slim-megaflex-total-ca-52004-42", title: "42", price: "289.99", available: true, image: null },
      { id: "calca-slim-megaflex-total-ca-52004-44", title: "44", price: "289.99", available: true, image: null },
      { id: "calca-slim-megaflex-total-ca-52004-46", title: "46", price: "289.99", available: true, image: null },
      { id: "calca-slim-megaflex-total-ca-52004-48", title: "48", price: "289.99", available: true, image: null },
    ],
  },
  {
    id: "calca-slim-megaflex-total-ca-52005",
    title: "Calça Slim Megaflex Total (CA 52005)",
    handle: "calca-slim-megaflex-total-ca-52005",
    description: "Calça masculina desenvolvida com tecido Megaflex, que oferece alta elasticidade e conforto superior. Caimento ajustado ao corpo, proporcionando mobilidade e estilo para o dia a dia. Referência: CA 52005. Composição: 68% Algodão · 10% Viscose · 20% Poliéster · 2% Elastano. Disponibilidade: Pronta Entrega.",
    descriptionHtml: "<p>Calça masculina desenvolvida com tecido Megaflex, que oferece alta elasticidade e conforto superior. Caimento ajustado ao corpo, proporcionando mobilidade e estilo para o dia a dia.</p><p><strong>Referência:</strong> CA 52005<br/><strong>Composição:</strong> 68% Algodão · 10% Viscose · 20% Poliéster · 2% Elastano<br/><strong>Disponibilidade:</strong> Pronta Entrega</p>",
    productType: "Calça Jeans",
    tags: ["calca", "slim", "pronta-entrega", "novidade", "ca-52005"],
    images: [
      img("p15_08", "Calça Slim Megaflex Total (CA 52005), frente"),
      img("p15_10", "Calça Slim Megaflex Total (CA 52005), detalhe"),
      img("p15_09", "Calça Slim Megaflex Total (CA 52005), costas"),
    ],
    variants: [
      { id: "calca-slim-megaflex-total-ca-52005-38", title: "38", price: "289.99", available: true, image: null },
      { id: "calca-slim-megaflex-total-ca-52005-40", title: "40", price: "289.99", available: true, image: null },
      { id: "calca-slim-megaflex-total-ca-52005-42", title: "42", price: "289.99", available: true, image: null },
      { id: "calca-slim-megaflex-total-ca-52005-44", title: "44", price: "289.99", available: true, image: null },
      { id: "calca-slim-megaflex-total-ca-52005-46", title: "46", price: "289.99", available: true, image: null },
      { id: "calca-slim-megaflex-total-ca-52005-48", title: "48", price: "289.99", available: true, image: null },
    ],
  },
  {
    id: "calca-slim-new-glui-mix-black-ca-52003",
    title: "Calça Slim New Glui Mix Black",
    handle: "calca-slim-new-glui-mix-black-ca-52003",
    description: "Modelagem slim que se ajusta ao corpo com conforto e estilo. Tecido com toque macio e acabamento premium. Referência: CA 52003. Composição: 67% Algodão · 13% Poliéster · 20% Elastano. Disponibilidade: Pronta Entrega.",
    descriptionHtml: "<p>Modelagem slim que se ajusta ao corpo com conforto e estilo. Tecido com toque macio e acabamento premium.</p><p><strong>Referência:</strong> CA 52003<br/><strong>Composição:</strong> 67% Algodão · 13% Poliéster · 20% Elastano<br/><strong>Disponibilidade:</strong> Pronta Entrega</p>",
    productType: "Calça Jeans",
    tags: ["calca", "slim", "pronta-entrega", "ca-52003"],
    images: [
      img("p16_02", "Calça Slim New Glui Mix Black, frente"),
      img("p16_03", "Calça Slim New Glui Mix Black, detalhe"),
      img("p16_04", "Calça Slim New Glui Mix Black, costas"),
    ],
    variants: [
      { id: "calca-slim-new-glui-mix-black-ca-52003-38", title: "38", price: "279.99", available: true, image: null },
      { id: "calca-slim-new-glui-mix-black-ca-52003-40", title: "40", price: "279.99", available: true, image: null },
      { id: "calca-slim-new-glui-mix-black-ca-52003-42", title: "42", price: "279.99", available: true, image: null },
      { id: "calca-slim-new-glui-mix-black-ca-52003-44", title: "44", price: "279.99", available: true, image: null },
      { id: "calca-slim-new-glui-mix-black-ca-52003-46", title: "46", price: "279.99", available: true, image: null },
      { id: "calca-slim-new-glui-mix-black-ca-52003-48", title: "48", price: "279.99", available: true, image: null },
    ],
  },
  {
    id: "calca-masculina-slim-ca-52001-c1",
    title: "Calça Masculina Slim (CA 52001 C-1)",
    handle: "calca-masculina-slim-ca-52001-c1",
    description: "Modelagem slim que se ajusta ao corpo com conforto e estilo. Tecido com toque macio e acabamento premium. Referência: CA 52001 C-1. Composição: 98% Algodão · 2% Elastano. Disponibilidade: Pronta Entrega.",
    descriptionHtml: "<p>Modelagem slim que se ajusta ao corpo com conforto e estilo. Tecido com toque macio e acabamento premium.</p><p><strong>Referência:</strong> CA 52001 C-1<br/><strong>Composição:</strong> 98% Algodão · 2% Elastano<br/><strong>Disponibilidade:</strong> Pronta Entrega</p>",
    productType: "Calça Jeans",
    tags: ["calca", "slim", "pronta-entrega", "ca-52001-c-1"],
    images: [
      img("p17_02", "Calça Masculina Slim (CA 52001 C-1), frente"),
      img("p17_03", "Calça Masculina Slim (CA 52001 C-1), detalhe"),
      img("p17_04", "Calça Masculina Slim (CA 52001 C-1), costas"),
    ],
    variants: [
      { id: "calca-masculina-slim-ca-52001-c1-38", title: "38", price: "279.99", available: true, image: null },
      { id: "calca-masculina-slim-ca-52001-c1-40", title: "40", price: "279.99", available: true, image: null },
      { id: "calca-masculina-slim-ca-52001-c1-42", title: "42", price: "279.99", available: true, image: null },
      { id: "calca-masculina-slim-ca-52001-c1-44", title: "44", price: "279.99", available: true, image: null },
      { id: "calca-masculina-slim-ca-52001-c1-46", title: "46", price: "279.99", available: true, image: null },
      { id: "calca-masculina-slim-ca-52001-c1-48", title: "48", price: "279.99", available: true, image: null },
    ],
  },
  {
    id: "calca-masculina-slim-legacy-ca-52006",
    title: "Calça Masculina Slim Legacy (CA 52006)",
    handle: "calca-masculina-slim-legacy-ca-52006",
    description: "Modelagem slim que se ajusta ao corpo com conforto e estilo. Confeccionada no tecido Legacy, com toque macio e acabamento premium. Referência: CA 52006 & CA 520006-01. Composição: 98% Algodão · 2% Elastano. Disponibilidade: Pronta Entrega.",
    descriptionHtml: "<p>Modelagem slim que se ajusta ao corpo com conforto e estilo. Confeccionada no tecido Legacy, com toque macio e acabamento premium.</p><p><strong>Referência:</strong> CA 52006 & CA 520006-01<br/><strong>Composição:</strong> 98% Algodão · 2% Elastano<br/><strong>Disponibilidade:</strong> Pronta Entrega</p>",
    productType: "Calça Jeans",
    tags: ["calca", "slim", "pronta-entrega", "ca-52006-e-ca-520006-01"],
    images: [
      img("p18_03", "Calça Masculina Slim Legacy (CA 52006), frente"),
      img("p18_01", "Calça Masculina Slim Legacy (CA 52006), detalhe"),
      img("p18_04", "Calça Masculina Slim Legacy (CA 52006), costas"),
      img("p18_02", "Calça Masculina Slim Legacy (CA 52006), close"),
    ],
    variants: [
      { id: "calca-masculina-slim-legacy-ca-52006-38", title: "38", price: "279.99", available: true, image: null },
      { id: "calca-masculina-slim-legacy-ca-52006-40", title: "40", price: "279.99", available: true, image: null },
      { id: "calca-masculina-slim-legacy-ca-52006-42", title: "42", price: "279.99", available: true, image: null },
      { id: "calca-masculina-slim-legacy-ca-52006-44", title: "44", price: "279.99", available: true, image: null },
      { id: "calca-masculina-slim-legacy-ca-52006-46", title: "46", price: "279.99", available: true, image: null },
      { id: "calca-masculina-slim-legacy-ca-52006-48", title: "48", price: "279.99", available: true, image: null },
    ],
  },
  {
    id: "calca-masculina-reta-ca-53001",
    title: "Calça Masculina Reta (CA 53001)",
    handle: "calca-masculina-reta-ca-53001",
    description: "Modelagem reta com caimento equilibrado, oferecendo conforto, liberdade de movimento e um visual atemporal. Toque macio e acabamento premium. Referência: CA 53001. Composição: 100% Algodão. Disponibilidade: Pronta Entrega.",
    descriptionHtml: "<p>Modelagem reta com caimento equilibrado, oferecendo conforto, liberdade de movimento e um visual atemporal. Toque macio e acabamento premium.</p><p><strong>Referência:</strong> CA 53001<br/><strong>Composição:</strong> 100% Algodão<br/><strong>Disponibilidade:</strong> Pronta Entrega</p>",
    productType: "Calça Jeans",
    tags: ["calca", "reta", "pronta-entrega", "ca-53001"],
    images: [
      img("p19_01", "Calça Masculina Reta (CA 53001), frente"),
      img("p19_02", "Calça Masculina Reta (CA 53001), detalhe"),
      img("p19_03", "Calça Masculina Reta (CA 53001), costas"),
    ],
    variants: [
      { id: "calca-masculina-reta-ca-53001-38", title: "38", price: "279.99", available: true, image: null },
      { id: "calca-masculina-reta-ca-53001-40", title: "40", price: "279.99", available: true, image: null },
      { id: "calca-masculina-reta-ca-53001-42", title: "42", price: "279.99", available: true, image: null },
      { id: "calca-masculina-reta-ca-53001-44", title: "44", price: "279.99", available: true, image: null },
      { id: "calca-masculina-reta-ca-53001-46", title: "46", price: "279.99", available: true, image: null },
      { id: "calca-masculina-reta-ca-53001-48", title: "48", price: "279.99", available: true, image: null },
    ],
  },
  {
    id: "calca-masculina-reta-ca-53003",
    title: "Calça Masculina Reta (CA 53003)",
    handle: "calca-masculina-reta-ca-53003",
    description: "Modelagem reta com caimento equilibrado, oferecendo conforto, liberdade de movimento e um visual atemporal. Toque macio e acabamento premium. Referência: CA 53003. Composição: 100% Algodão. Disponibilidade: Pronta Entrega.",
    descriptionHtml: "<p>Modelagem reta com caimento equilibrado, oferecendo conforto, liberdade de movimento e um visual atemporal. Toque macio e acabamento premium.</p><p><strong>Referência:</strong> CA 53003<br/><strong>Composição:</strong> 100% Algodão<br/><strong>Disponibilidade:</strong> Pronta Entrega</p>",
    productType: "Calça Jeans",
    tags: ["calca", "reta", "pronta-entrega", "ca-53003"],
    images: [
      img("p20_02", "Calça Masculina Reta (CA 53003), frente"),
      img("p20_03", "Calça Masculina Reta (CA 53003), detalhe"),
      img("p20_01", "Calça Masculina Reta (CA 53003), costas"),
    ],
    variants: [
      { id: "calca-masculina-reta-ca-53003-38", title: "38", price: "279.99", available: true, image: null },
      { id: "calca-masculina-reta-ca-53003-40", title: "40", price: "279.99", available: true, image: null },
      { id: "calca-masculina-reta-ca-53003-42", title: "42", price: "279.99", available: true, image: null },
      { id: "calca-masculina-reta-ca-53003-44", title: "44", price: "279.99", available: true, image: null },
      { id: "calca-masculina-reta-ca-53003-46", title: "46", price: "279.99", available: true, image: null },
      { id: "calca-masculina-reta-ca-53003-48", title: "48", price: "279.99", available: true, image: null },
    ],
  },
  {
    id: "calca-sport-fino-ca-51005",
    title: "Calça Sport Fino (CA 51005)",
    handle: "calca-sport-fino-ca-51005",
    description: "Modelagem Sport Fino com caimento moderno, unindo conforto, mobilidade e sofisticação na medida certa. Confeccionada no tecido Legacy, com toque macio e acabamento premium. Referência: CA 51005. Composição: 100% Algodão. Cores disponíveis: Azul-marinho · Bege · Preto. Disponibilidade: Pronta Entrega.",
    descriptionHtml: "<p>Modelagem Sport Fino com caimento moderno, unindo conforto, mobilidade e sofisticação na medida certa. Confeccionada no tecido Legacy, com toque macio e acabamento premium.</p><p><strong>Referência:</strong> CA 51005<br/><strong>Composição:</strong> 100% Algodão<br/><strong>Cores:</strong> Azul-marinho · Bege · Preto<br/><strong>Disponibilidade:</strong> Pronta Entrega</p>",
    productType: "Calça Sport Fino",
    tags: ["calca", "sport-fino", "pronta-entrega", "ca-51005"],
    images: [
      img("p21_03", "Calça Sport Fino (CA 51005), frente"),
      img("p21_01", "Calça Sport Fino (CA 51005), detalhe"),
      img("p21_02", "Calça Sport Fino (CA 51005), costas"),
    ],
    variants: [
      { id: "calca-sport-fino-ca-51005-38", title: "38", price: "269.99", available: true, image: null },
      { id: "calca-sport-fino-ca-51005-40", title: "40", price: "269.99", available: true, image: null },
      { id: "calca-sport-fino-ca-51005-42", title: "42", price: "269.99", available: true, image: null },
      { id: "calca-sport-fino-ca-51005-44", title: "44", price: "269.99", available: true, image: null },
      { id: "calca-sport-fino-ca-51005-46", title: "46", price: "269.99", available: true, image: null },
      { id: "calca-sport-fino-ca-51005-48", title: "48", price: "269.99", available: true, image: null },
    ],
  },
  {
    id: "calca-freebong-sport-fino-ca-058",
    title: "Calça Freebong Sport Fino (CA 058)",
    handle: "calca-freebong-sport-fino-ca-058",
    description: "O equilíbrio perfeito entre elegância e casualidade. Com caimento moderno e tecido confortável, é ideal para quem busca versatilidade no dia a dia sem abrir mão de estilo. Referência: CA 058. Composição: 67% Algodão · 31% Poliéster · 2% Elastano. Disponibilidade: Programação.",
    descriptionHtml: "<p>O equilíbrio perfeito entre elegância e casualidade. Com caimento moderno e tecido confortável, é ideal para quem busca versatilidade no dia a dia sem abrir mão de estilo.</p><p><strong>Referência:</strong> CA 058<br/><strong>Composição:</strong> 67% Algodão · 31% Poliéster · 2% Elastano<br/><strong>Disponibilidade:</strong> Programação</p>",
    productType: "Calça Sport Fino",
    tags: ["calca", "sport-fino", "programacao", "ca-058"],
    images: [
      img("p22_02", "Calça Freebong Sport Fino (CA 058), frente"),
      img("p22_03", "Calça Freebong Sport Fino (CA 058), detalhe"),
    ],
    variants: [
      { id: "calca-freebong-sport-fino-ca-058-38", title: "38", price: "269.99", available: true, image: null },
      { id: "calca-freebong-sport-fino-ca-058-40", title: "40", price: "269.99", available: true, image: null },
      { id: "calca-freebong-sport-fino-ca-058-42", title: "42", price: "269.99", available: true, image: null },
      { id: "calca-freebong-sport-fino-ca-058-44", title: "44", price: "269.99", available: true, image: null },
      { id: "calca-freebong-sport-fino-ca-058-46", title: "46", price: "269.99", available: true, image: null },
      { id: "calca-freebong-sport-fino-ca-058-48", title: "48", price: "269.99", available: true, image: null },
    ],
  },
  {
    id: "calca-fbg-roma-tec-ca-054",
    title: "Calça FBG Roma Tec",
    handle: "calca-fbg-roma-tec-ca-054",
    description: "Calça de alfaiataria em tecido Tec, com caimento estruturado e toque confortável. Une elegância e tecnologia, oferecendo praticidade, durabilidade e um visual sofisticado para qualquer ocasião. Referência: CA 054. Composição: 66% Viscose · 27% Poliéster · 7% Elastano. Disponibilidade: Pronta Entrega.",
    descriptionHtml: "<p>Calça de alfaiataria em tecido Tec, com caimento estruturado e toque confortável. Une elegância e tecnologia, oferecendo praticidade, durabilidade e um visual sofisticado para qualquer ocasião.</p><p><strong>Referência:</strong> CA 054<br/><strong>Composição:</strong> 66% Viscose · 27% Poliéster · 7% Elastano<br/><strong>Disponibilidade:</strong> Pronta Entrega</p>",
    productType: "Calça Alfaiataria",
    tags: ["calca", "alfaiataria", "pronta-entrega", "ca-054"],
    images: [
      img("p23_02", "Calça FBG Roma Tec, frente"),
      img("p23_03", "Calça FBG Roma Tec, detalhe"),
      img("p23_04", "Calça FBG Roma Tec, costas"),
    ],
    variants: [
      { id: "calca-fbg-roma-tec-ca-054-38", title: "38", price: "269.99", available: true, image: null },
      { id: "calca-fbg-roma-tec-ca-054-40", title: "40", price: "269.99", available: true, image: null },
      { id: "calca-fbg-roma-tec-ca-054-42", title: "42", price: "269.99", available: true, image: null },
      { id: "calca-fbg-roma-tec-ca-054-44", title: "44", price: "269.99", available: true, image: null },
      { id: "calca-fbg-roma-tec-ca-054-46", title: "46", price: "269.99", available: true, image: null },
      { id: "calca-fbg-roma-tec-ca-054-48", title: "48", price: "269.99", available: true, image: null },
    ],
  },
  {
    id: "calca-cargo-freebong-ca-006",
    title: "Calça Cargo Freebong",
    handle: "calca-cargo-freebong-ca-006",
    description: "A Calça Cargo Freebong traz uma proposta moderna, funcional e cheia de presença. Modelagem confortável e bolsos laterais utilitários entregam praticidade sem abrir mão do estilo. Caimento marcante e identidade Freebong em cada detalhe. Referência: CA 006. Composição: 98% Algodão · 2% Elastano. Disponibilidade: Pronta Entrega.",
    descriptionHtml: "<p>A Calça Cargo Freebong traz uma proposta moderna, funcional e cheia de presença. Modelagem confortável e bolsos laterais utilitários entregam praticidade sem abrir mão do estilo. Caimento marcante e identidade Freebong em cada detalhe.</p><p><strong>Referência:</strong> CA 006<br/><strong>Composição:</strong> 98% Algodão · 2% Elastano<br/><strong>Disponibilidade:</strong> Pronta Entrega</p>",
    productType: "Calça Cargo",
    tags: ["calca", "cargo", "pronta-entrega", "ca-006"],
    images: [

      img("p24_02", "Calça Cargo Freebong, frente"),
      img("p24_04", "Calça Cargo Freebong, detalhe"),
      img("p24_03", "Calça Cargo Freebong, costas"),
    ],
    variants: [
      { id: "calca-cargo-freebong-ca-006-38", title: "38", price: "279.99", available: true, image: null },
      { id: "calca-cargo-freebong-ca-006-40", title: "40", price: "279.99", available: true, image: null },
      { id: "calca-cargo-freebong-ca-006-42", title: "42", price: "279.99", available: true, image: null },
      { id: "calca-cargo-freebong-ca-006-44", title: "44", price: "279.99", available: true, image: null },
      { id: "calca-cargo-freebong-ca-006-46", title: "46", price: "279.99", available: true, image: null },
      { id: "calca-cargo-freebong-ca-006-48", title: "48", price: "279.99", available: true, image: null },
    ],
  },
  {
    id: "bermuda-queen-triblend-be-062-03",
    title: "Bermuda Queen Triblend (BE 062-03)",
    handle: "bermuda-queen-triblend-be-062-03",
    description: "Bermuda desenvolvida com o tecido Queen Triblend, que combina leveza, resistência e toque macio. Ideal para quem busca conforto no dia a dia sem abrir mão de um visual moderno e versátil. Referência: BE 062-03. Composição: 98% Algodão · 2% Elastano. Disponibilidade: Programação.",
    descriptionHtml: "<p>Bermuda desenvolvida com o tecido Queen Triblend, que combina leveza, resistência e toque macio. Ideal para quem busca conforto no dia a dia sem abrir mão de um visual moderno e versátil.</p><p><strong>Referência:</strong> BE 062-03<br/><strong>Composição:</strong> 98% Algodão · 2% Elastano<br/><strong>Disponibilidade:</strong> Programação</p>",
    productType: "Bermuda Jeans",
    tags: ["bermuda", "bermuda-jeans", "programacao", "be-062-03"],
    images: [
      img("p27_01", "Bermuda Queen Triblend (BE 062-03), frente"),
      img("p27_02", "Bermuda Queen Triblend (BE 062-03), detalhe"),
      img("p27_03", "Bermuda Queen Triblend (BE 062-03), costas"),
    ],
    variants: [
      { id: "bermuda-queen-triblend-be-062-03-38", title: "38", price: "229.99", available: true, image: null },
      { id: "bermuda-queen-triblend-be-062-03-40", title: "40", price: "229.99", available: true, image: null },
      { id: "bermuda-queen-triblend-be-062-03-42", title: "42", price: "229.99", available: true, image: null },
      { id: "bermuda-queen-triblend-be-062-03-44", title: "44", price: "229.99", available: true, image: null },
      { id: "bermuda-queen-triblend-be-062-03-46", title: "46", price: "229.99", available: true, image: null },
      { id: "bermuda-queen-triblend-be-062-03-48", title: "48", price: "229.99", available: true, image: null },
    ],
  },
  {
    id: "bermuda-queen-triblend-be-062-01",
    title: "Bermuda Queen Triblend (BE 062-01)",
    handle: "bermuda-queen-triblend-be-062-01",
    description: "Bermuda desenvolvida com o tecido Queen Triblend, que combina leveza, resistência e toque macio. Ideal para quem busca conforto no dia a dia sem abrir mão de um visual moderno e versátil. Referência: BE 062-01. Composição: 98% Algodão · 2% Elastano. Disponibilidade: Programação.",
    descriptionHtml: "<p>Bermuda desenvolvida com o tecido Queen Triblend, que combina leveza, resistência e toque macio. Ideal para quem busca conforto no dia a dia sem abrir mão de um visual moderno e versátil.</p><p><strong>Referência:</strong> BE 062-01<br/><strong>Composição:</strong> 98% Algodão · 2% Elastano<br/><strong>Disponibilidade:</strong> Programação</p>",
    productType: "Bermuda Jeans",
    tags: ["bermuda", "bermuda-jeans", "programacao", "be-062-01"],
    images: [
      img("p27_04", "Bermuda Queen Triblend (BE 062-01), frente"),
      img("p27_05", "Bermuda Queen Triblend (BE 062-01), detalhe"),
      img("p27_06", "Bermuda Queen Triblend (BE 062-01), costas"),
    ],
    variants: [
      { id: "bermuda-queen-triblend-be-062-01-38", title: "38", price: "229.99", available: true, image: null },
      { id: "bermuda-queen-triblend-be-062-01-40", title: "40", price: "229.99", available: true, image: null },
      { id: "bermuda-queen-triblend-be-062-01-42", title: "42", price: "229.99", available: true, image: null },
      { id: "bermuda-queen-triblend-be-062-01-44", title: "44", price: "229.99", available: true, image: null },
      { id: "bermuda-queen-triblend-be-062-01-46", title: "46", price: "229.99", available: true, image: null },
      { id: "bermuda-queen-triblend-be-062-01-48", title: "48", price: "229.99", available: true, image: null },
    ],
  },
  {
    id: "bermuda-legacy-be-063-01",
    title: "Bermuda Legacy",
    handle: "bermuda-legacy-be-063-01",
    description: "Bermuda Legacy que combina leveza, resistência e toque macio. Ideal para quem busca conforto no dia a dia sem abrir mão de um visual moderno e versátil. Referência: BE 063-01. Composição: 98% Algodão · 2% Elastano. Disponibilidade: Programação.",
    descriptionHtml: "<p>Bermuda Legacy que combina leveza, resistência e toque macio. Ideal para quem busca conforto no dia a dia sem abrir mão de um visual moderno e versátil.</p><p><strong>Referência:</strong> BE 063-01<br/><strong>Composição:</strong> 98% Algodão · 2% Elastano<br/><strong>Disponibilidade:</strong> Programação</p>",
    productType: "Bermuda Jeans",
    tags: ["bermuda", "bermuda-jeans", "programacao", "be-063-01"],
    images: [
      img("p28_01", "Bermuda Legacy, frente"),
      img("p28_02", "Bermuda Legacy, detalhe"),
      img("p28_03", "Bermuda Legacy, costas"),
    ],
    variants: [
      { id: "bermuda-legacy-be-063-01-38", title: "38", price: "229.99", available: true, image: null },
      { id: "bermuda-legacy-be-063-01-40", title: "40", price: "229.99", available: true, image: null },
      { id: "bermuda-legacy-be-063-01-42", title: "42", price: "229.99", available: true, image: null },
      { id: "bermuda-legacy-be-063-01-44", title: "44", price: "229.99", available: true, image: null },
      { id: "bermuda-legacy-be-063-01-46", title: "46", price: "229.99", available: true, image: null },
      { id: "bermuda-legacy-be-063-01-48", title: "48", price: "229.99", available: true, image: null },
    ],
  },
  {
    id: "bermuda-black-be-051",
    title: "Bermuda Black",
    handle: "bermuda-black-be-051",
    description: "Bermuda desenvolvida com o tecido Black, que oferece cor intensa e duradoura, mantendo o preto vivo por muito mais tempo. Toque macio, ótimo caimento e resistência no uso diário. Referência: BE 051. Composição: 98% Algodão · 2% Elastano. Disponibilidade: Programação.",
    descriptionHtml: "<p>Bermuda desenvolvida com o tecido Black, que oferece cor intensa e duradoura, mantendo o preto vivo por muito mais tempo. Toque macio, ótimo caimento e resistência no uso diário.</p><p><strong>Referência:</strong> BE 051<br/><strong>Composição:</strong> 98% Algodão · 2% Elastano<br/><strong>Disponibilidade:</strong> Programação</p>",
    productType: "Bermuda Jeans",
    tags: ["bermuda", "bermuda-jeans", "programacao", "be-051"],
    images: [
      img("p29_01", "Bermuda Black, frente"),
      img("p29_02", "Bermuda Black, detalhe"),
      img("p29_03", "Bermuda Black, costas"),
    ],
    variants: [
      { id: "bermuda-black-be-051-38", title: "38", price: "229.99", available: true, image: null },
      { id: "bermuda-black-be-051-40", title: "40", price: "229.99", available: true, image: null },
      { id: "bermuda-black-be-051-42", title: "42", price: "229.99", available: true, image: null },
      { id: "bermuda-black-be-051-44", title: "44", price: "229.99", available: true, image: null },
      { id: "bermuda-black-be-051-46", title: "46", price: "229.99", available: true, image: null },
      { id: "bermuda-black-be-051-48", title: "48", price: "229.99", available: true, image: null },
    ],
  },
  {
    id: "bermuda-up-black-be-54001",
    title: "Bermuda Up Black",
    handle: "bermuda-up-black-be-54001",
    description: "Bermuda confeccionada em tecido Up Black, com tecnologia que garante alta elasticidade e recuperação, proporcionando liberdade de movimento sem perder a forma. Preto profundo aliado ao conforto extremo. Referência: BE 54001. Composição: 98% Algodão · 2% Elastano. Disponibilidade: Pronta Entrega.",
    descriptionHtml: "<p>Bermuda confeccionada em tecido Up Black, com tecnologia que garante alta elasticidade e recuperação, proporcionando liberdade de movimento sem perder a forma. Preto profundo aliado ao conforto extremo.</p><p><strong>Referência:</strong> BE 54001<br/><strong>Composição:</strong> 98% Algodão · 2% Elastano<br/><strong>Disponibilidade:</strong> Pronta Entrega</p>",
    productType: "Bermuda Jeans",
    tags: ["bermuda", "bermuda-jeans", "pronta-entrega", "be-54001"],
    images: [
      img("p29_04", "Bermuda Up Black, frente"),
      img("p29_05", "Bermuda Up Black, detalhe"),
      img("p29_06", "Bermuda Up Black, costas"),
    ],
    variants: [
      { id: "bermuda-up-black-be-54001-38", title: "38", price: "229.99", available: true, image: null },
      { id: "bermuda-up-black-be-54001-40", title: "40", price: "229.99", available: true, image: null },
      { id: "bermuda-up-black-be-54001-42", title: "42", price: "229.99", available: true, image: null },
      { id: "bermuda-up-black-be-54001-44", title: "44", price: "229.99", available: true, image: null },
      { id: "bermuda-up-black-be-54001-46", title: "46", price: "229.99", available: true, image: null },
      { id: "bermuda-up-black-be-54001-48", title: "48", price: "229.99", available: true, image: null },
    ],
  },
  {
    id: "bermuda-blackout-be-012-02",
    title: "Bermuda Blackout (BE 012-02)",
    handle: "bermuda-blackout-be-012-02",
    description: "Bermuda confeccionada com o tecido Blackout, desenvolvido para oferecer preto intenso com máxima fixação de cor, evitando desbotamento mesmo após várias lavagens. Toque firme, excelente durabilidade e caimento estruturado. Referência: BE 012-02. Composição: 98% Algodão · 2% Elastano. Disponibilidade: Pronta Entrega.",
    descriptionHtml: "<p>Bermuda confeccionada com o tecido Blackout, desenvolvido para oferecer preto intenso com máxima fixação de cor, evitando desbotamento mesmo após várias lavagens. Toque firme, excelente durabilidade e caimento estruturado.</p><p><strong>Referência:</strong> BE 012-02<br/><strong>Composição:</strong> 98% Algodão · 2% Elastano<br/><strong>Disponibilidade:</strong> Pronta Entrega</p>",
    productType: "Bermuda Jeans",
    tags: ["bermuda", "bermuda-jeans", "pronta-entrega", "be-012-02"],
    images: [
      img("p30_01", "Bermuda Blackout (BE 012-02), frente"),
      img("p30_02", "Bermuda Blackout (BE 012-02), detalhe"),
      img("p30_03", "Bermuda Blackout (BE 012-02), costas"),
    ],
    variants: [
      { id: "bermuda-blackout-be-012-02-38", title: "38", price: "229.99", available: true, image: null },
      { id: "bermuda-blackout-be-012-02-40", title: "40", price: "229.99", available: true, image: null },
      { id: "bermuda-blackout-be-012-02-42", title: "42", price: "229.99", available: true, image: null },
      { id: "bermuda-blackout-be-012-02-44", title: "44", price: "229.99", available: true, image: null },
      { id: "bermuda-blackout-be-012-02-46", title: "46", price: "229.99", available: true, image: null },
      { id: "bermuda-blackout-be-012-02-48", title: "48", price: "229.99", available: true, image: null },
    ],
  },
  {
    id: "bermuda-masc-tec-craquelada-be-045-02",
    title: "Bermuda Masc. Tec Craquelada",
    handle: "bermuda-masc-tec-craquelada-be-045-02",
    description: "Bermuda confeccionada em tecido Tec, com acabamento craquelado que traz textura exclusiva e visual moderno. Une tecnologia, resistência e um toque diferenciado, garantindo caimento impecável. Referência: BE 045-02. Composição: 98% Algodão · 2% Elastano. Disponibilidade: Pronta Entrega.",
    descriptionHtml: "<p>Bermuda confeccionada em tecido Tec, com acabamento craquelado que traz textura exclusiva e visual moderno. Une tecnologia, resistência e um toque diferenciado, garantindo caimento impecável.</p><p><strong>Referência:</strong> BE 045-02<br/><strong>Composição:</strong> 98% Algodão · 2% Elastano<br/><strong>Disponibilidade:</strong> Pronta Entrega</p>",
    productType: "Bermuda Jeans",
    tags: ["bermuda", "bermuda-jeans", "pronta-entrega", "be-045-02"],
    images: [
      img("p30_04", "Bermuda Masc. Tec Craquelada, frente"),
      img("p30_05", "Bermuda Masc. Tec Craquelada, detalhe"),
      img("p30_06", "Bermuda Masc. Tec Craquelada, costas"),
    ],
    variants: [
      { id: "bermuda-masc-tec-craquelada-be-045-02-38", title: "38", price: "229.99", available: true, image: null },
      { id: "bermuda-masc-tec-craquelada-be-045-02-40", title: "40", price: "229.99", available: true, image: null },
      { id: "bermuda-masc-tec-craquelada-be-045-02-42", title: "42", price: "229.99", available: true, image: null },
      { id: "bermuda-masc-tec-craquelada-be-045-02-44", title: "44", price: "229.99", available: true, image: null },
      { id: "bermuda-masc-tec-craquelada-be-045-02-46", title: "46", price: "229.99", available: true, image: null },
      { id: "bermuda-masc-tec-craquelada-be-045-02-48", title: "48", price: "229.99", available: true, image: null },
    ],
  },
  {
    id: "bermuda-blackout-be-045-01",
    title: "Bermuda Blackout (BE 045-01)",
    handle: "bermuda-blackout-be-045-01",
    description: "Bermuda confeccionada com o tecido Blackout, desenvolvido para oferecer preto intenso com máxima fixação de cor, evitando desbotamento mesmo após várias lavagens. Toque firme, excelente durabilidade e caimento estruturado. Referência: BE 045-01. Composição: 98% Algodão · 2% Elastano. Disponibilidade: Pronta Entrega.",
    descriptionHtml: "<p>Bermuda confeccionada com o tecido Blackout, desenvolvido para oferecer preto intenso com máxima fixação de cor, evitando desbotamento mesmo após várias lavagens. Toque firme, excelente durabilidade e caimento estruturado.</p><p><strong>Referência:</strong> BE 045-01<br/><strong>Composição:</strong> 98% Algodão · 2% Elastano<br/><strong>Disponibilidade:</strong> Pronta Entrega</p>",
    productType: "Bermuda Jeans",
    tags: ["bermuda", "bermuda-jeans", "pronta-entrega", "be-045-01"],
    images: [
      img("p31_01", "Bermuda Blackout (BE 045-01), frente"),
      img("p31_02", "Bermuda Blackout (BE 045-01), detalhe"),
      img("p31_03", "Bermuda Blackout (BE 045-01), costas"),
    ],
    variants: [
      { id: "bermuda-blackout-be-045-01-38", title: "38", price: "229.99", available: true, image: null },
      { id: "bermuda-blackout-be-045-01-40", title: "40", price: "229.99", available: true, image: null },
      { id: "bermuda-blackout-be-045-01-42", title: "42", price: "229.99", available: true, image: null },
      { id: "bermuda-blackout-be-045-01-44", title: "44", price: "229.99", available: true, image: null },
      { id: "bermuda-blackout-be-045-01-46", title: "46", price: "229.99", available: true, image: null },
      { id: "bermuda-blackout-be-045-01-48", title: "48", price: "229.99", available: true, image: null },
    ],
  },
  {
    id: "bermuda-tec-white-denim-be-055",
    title: "Bermuda Tec White Denim",
    handle: "bermuda-tec-white-denim-be-055",
    description: "Bermuda desenvolvida em Tec White Denim, com visual clean e sofisticado. O tecido combina estrutura com leve elasticidade, proporcionando conforto, ótimo caimento e liberdade de movimento. Referência: BE 055. Composição: 98% Algodão · 2% Elastano. Disponibilidade: Pronta Entrega.",
    descriptionHtml: "<p>Bermuda desenvolvida em Tec White Denim, com visual clean e sofisticado. O tecido combina estrutura com leve elasticidade, proporcionando conforto, ótimo caimento e liberdade de movimento.</p><p><strong>Referência:</strong> BE 055<br/><strong>Composição:</strong> 98% Algodão · 2% Elastano<br/><strong>Disponibilidade:</strong> Pronta Entrega</p>",
    productType: "Bermuda Jeans",
    tags: ["bermuda", "bermuda-jeans", "pronta-entrega", "be-055"],
    images: [
      img("p31_04", "Bermuda Tec White Denim, frente"),
      img("p31_05", "Bermuda Tec White Denim, detalhe"),
      img("p31_06", "Bermuda Tec White Denim, costas"),
    ],
    variants: [
      { id: "bermuda-tec-white-denim-be-055-38", title: "38", price: "229.99", available: true, image: null },
      { id: "bermuda-tec-white-denim-be-055-40", title: "40", price: "229.99", available: true, image: null },
      { id: "bermuda-tec-white-denim-be-055-42", title: "42", price: "229.99", available: true, image: null },
      { id: "bermuda-tec-white-denim-be-055-44", title: "44", price: "229.99", available: true, image: null },
      { id: "bermuda-tec-white-denim-be-055-46", title: "46", price: "229.99", available: true, image: null },
      { id: "bermuda-tec-white-denim-be-055-48", title: "48", price: "229.99", available: true, image: null },
    ],
  },
  {
    id: "bermuda-trad-be-010-02",
    title: "Bermuda Trad (BE 010-02)",
    handle: "bermuda-trad-be-010-02",
    description: "Bermuda produzida em 100% algodão, com toque natural e alta respirabilidade. O destaque fica por conta da barra desfiada no estilo jogador, que traz um visual despojado e autêntico. Referência: BE 010-02. Composição: 100% Algodão. Disponibilidade: Pronta Entrega.",
    descriptionHtml: "<p>Bermuda produzida em 100% algodão, com toque natural e alta respirabilidade. O destaque fica por conta da barra desfiada no estilo jogador, que traz um visual despojado e autêntico.</p><p><strong>Referência:</strong> BE 010-02<br/><strong>Composição:</strong> 100% Algodão<br/><strong>Disponibilidade:</strong> Pronta Entrega</p>",
    productType: "Bermuda Jeans",
    tags: ["bermuda", "bermuda-jeans", "pronta-entrega", "be-010-02"],
    images: [
      img("p32_01", "Bermuda Trad (BE 010-02), frente"),
      img("p32_02", "Bermuda Trad (BE 010-02), detalhe"),
      img("p32_03", "Bermuda Trad (BE 010-02), costas"),
    ],
    variants: [
      { id: "bermuda-trad-be-010-02-38", title: "38", price: "229.99", available: true, image: null },
      { id: "bermuda-trad-be-010-02-40", title: "40", price: "229.99", available: true, image: null },
      { id: "bermuda-trad-be-010-02-42", title: "42", price: "229.99", available: true, image: null },
      { id: "bermuda-trad-be-010-02-44", title: "44", price: "229.99", available: true, image: null },
      { id: "bermuda-trad-be-010-02-46", title: "46", price: "229.99", available: true, image: null },
      { id: "bermuda-trad-be-010-02-48", title: "48", price: "229.99", available: true, image: null },
    ],
  },
  {
    id: "bermuda-trad-be-010-10",
    title: "Bermuda Trad (BE 010-10)",
    handle: "bermuda-trad-be-010-10",
    description: "Bermuda produzida em 100% algodão, com toque natural e alta respirabilidade. O destaque fica por conta da barra desfiada no estilo jogador, que traz um visual despojado e autêntico. Referência: BE 010-10. Composição: 100% Algodão. Disponibilidade: Pronta Entrega.",
    descriptionHtml: "<p>Bermuda produzida em 100% algodão, com toque natural e alta respirabilidade. O destaque fica por conta da barra desfiada no estilo jogador, que traz um visual despojado e autêntico.</p><p><strong>Referência:</strong> BE 010-10<br/><strong>Composição:</strong> 100% Algodão<br/><strong>Disponibilidade:</strong> Pronta Entrega</p>",
    productType: "Bermuda Jeans",
    tags: ["bermuda", "bermuda-jeans", "pronta-entrega", "be-010-10"],
    images: [
      img("p32_04", "Bermuda Trad (BE 010-10), frente"),
      img("p32_05", "Bermuda Trad (BE 010-10), detalhe"),
      img("p32_06", "Bermuda Trad (BE 010-10), costas"),
    ],
    variants: [
      { id: "bermuda-trad-be-010-10-38", title: "38", price: "229.99", available: true, image: null },
      { id: "bermuda-trad-be-010-10-40", title: "40", price: "229.99", available: true, image: null },
      { id: "bermuda-trad-be-010-10-42", title: "42", price: "229.99", available: true, image: null },
      { id: "bermuda-trad-be-010-10-44", title: "44", price: "229.99", available: true, image: null },
      { id: "bermuda-trad-be-010-10-46", title: "46", price: "229.99", available: true, image: null },
      { id: "bermuda-trad-be-010-10-48", title: "48", price: "229.99", available: true, image: null },
    ],
  },
  {
    id: "bermuda-cargo-freebong-be-009",
    title: "Bermuda Cargo Freebong",
    handle: "bermuda-cargo-freebong-be-009",
    description: "A Bermuda Cargo Freebong é a escolha certa para quem busca conforto, estilo e funcionalidade em uma única peça. Bolsos laterais amplos, modelagem atual e acabamento premium. Uma peça forte, prática e com presença. Referência: BE 009. Composição: 98% Algodão · 2% Elastano. Disponibilidade: Pronta Entrega.",
    descriptionHtml: "<p>A Bermuda Cargo Freebong é a escolha certa para quem busca conforto, estilo e funcionalidade em uma única peça. Bolsos laterais amplos, modelagem atual e acabamento premium. Uma peça forte, prática e com presença.</p><p><strong>Referência:</strong> BE 009<br/><strong>Composição:</strong> 98% Algodão · 2% Elastano<br/><strong>Disponibilidade:</strong> Pronta Entrega</p>",
    productType: "Bermuda Cargo",
    tags: ["bermuda", "bermuda-cargo", "pronta-entrega", "be-009"],
    images: [

      img("p33_02", "Bermuda Cargo Freebong, frente"),
      img("p33_04", "Bermuda Cargo Freebong, detalhe"),
      img("p33_03", "Bermuda Cargo Freebong, costas"),
    ],
    variants: [
      { id: "bermuda-cargo-freebong-be-009-38", title: "38", price: "229.99", available: true, image: null },
      { id: "bermuda-cargo-freebong-be-009-40", title: "40", price: "229.99", available: true, image: null },
      { id: "bermuda-cargo-freebong-be-009-42", title: "42", price: "229.99", available: true, image: null },
      { id: "bermuda-cargo-freebong-be-009-44", title: "44", price: "229.99", available: true, image: null },
      { id: "bermuda-cargo-freebong-be-009-46", title: "46", price: "229.99", available: true, image: null },
      { id: "bermuda-cargo-freebong-be-009-48", title: "48", price: "229.99", available: true, image: null },
    ],
  },
  {
    id: "bermuda-sport-fino-be-056",
    title: "Bermuda Sport Fino",
    handle: "bermuda-sport-fino-be-056",
    description: "Bermuda confeccionada em sarja de alta qualidade, com toque macio e excelente resistência. Caimento alinhado e acabamento refinado, transita facilmente entre o casual e o mais arrumado. Referência: BE 056. Composição: 67% Algodão · 31% Poliéster · 2% Elastano. Cores disponíveis: Preto · Cinza · Bege. Disponibilidade: Pronta Entrega.",
    descriptionHtml: "<p>Bermuda confeccionada em sarja de alta qualidade, com toque macio e excelente resistência. Caimento alinhado e acabamento refinado, transita facilmente entre o casual e o mais arrumado.</p><p><strong>Referência:</strong> BE 056<br/><strong>Composição:</strong> 67% Algodão · 31% Poliéster · 2% Elastano<br/><strong>Cores:</strong> Preto · Cinza · Bege<br/><strong>Disponibilidade:</strong> Pronta Entrega</p>",
    productType: "Bermuda Sarja",
    tags: ["bermuda", "bermuda-sarja", "pronta-entrega", "be-056"],
    images: [
      img("p34_02", "Bermuda Sport Fino, frente"),
      img("p34_03", "Bermuda Sport Fino, detalhe"),
      img("p34_04", "Bermuda Sport Fino, costas"),
    ],
    variants: [
      { id: "bermuda-sport-fino-be-056-38", title: "38", price: "219.99", available: true, image: null },
      { id: "bermuda-sport-fino-be-056-40", title: "40", price: "219.99", available: true, image: null },
      { id: "bermuda-sport-fino-be-056-42", title: "42", price: "219.99", available: true, image: null },
      { id: "bermuda-sport-fino-be-056-44", title: "44", price: "219.99", available: true, image: null },
      { id: "bermuda-sport-fino-be-056-46", title: "46", price: "219.99", available: true, image: null },
      { id: "bermuda-sport-fino-be-056-48", title: "48", price: "219.99", available: true, image: null },
    ],
  },
  {
    id: "bermuda-roma-tec-be-053",
    title: "Bermuda Roma Tec",
    handle: "bermuda-roma-tec-be-053",
    description: "Bermuda Roma desenvolvida em tecido Tec da Santista, com caimento de alfaiataria que traz elegância e sofisticação. Estrutura leve, toque confortável e ótimo ajuste ao corpo. Referência: BE 053. Composição: 66% Viscose · 27% Poliéster · 7% Elastano. Cores disponíveis: Preto · Chumbo · Bege. Disponibilidade: Pronta Entrega.",
    descriptionHtml: "<p>Bermuda Roma desenvolvida em tecido Tec da Santista, com caimento de alfaiataria que traz elegância e sofisticação. Estrutura leve, toque confortável e ótimo ajuste ao corpo.</p><p><strong>Referência:</strong> BE 053<br/><strong>Composição:</strong> 66% Viscose · 27% Poliéster · 7% Elastano<br/><strong>Cores:</strong> Preto · Chumbo · Bege<br/><strong>Disponibilidade:</strong> Pronta Entrega</p>",
    productType: "Bermuda Alfaiataria",
    tags: ["bermuda", "bermuda-alfaiataria", "pronta-entrega", "be-053"],
    images: [
      img("p35_02", "Bermuda Roma Tec, frente"),
      img("p35_03", "Bermuda Roma Tec, detalhe"),
      img("p35_04", "Bermuda Roma Tec, costas"),
    ],
    variants: [
      { id: "bermuda-roma-tec-be-053-m", title: "M", price: "219.99", available: true, image: null },
      { id: "bermuda-roma-tec-be-053-g", title: "G", price: "219.99", available: true, image: null },
      { id: "bermuda-roma-tec-be-053-gg", title: "GG", price: "219.99", available: true, image: null },
    ],
  },
  {
    id: "jaqueta-new-park-lazuli-clara-jq-002-c2",
    title: "Jaqueta New Park Lazuli Clara",
    handle: "jaqueta-new-park-lazuli-clara-jq-002-c2",
    description: "Clássica e indispensável. Desenvolvida com tecido premium que combina leveza e resistência. O efeito estonado garante um visual autêntico e atemporal. Modelagem tradicional com caimento perfeito, gola clássica, bolsos funcionais e etiqueta exclusiva Freebong. Jeans claro com efeito estonado. Referência: JQ 002-C2. Composição: 100% Algodão. Disponibilidade: Pronta Entrega.",
    descriptionHtml: "<p>Clássica e indispensável. Desenvolvida com tecido premium que combina leveza e resistência. O efeito estonado garante um visual autêntico e atemporal. Modelagem tradicional com caimento perfeito, gola clássica, bolsos funcionais e etiqueta exclusiva Freebong. Jeans claro com efeito estonado.</p><p><strong>Referência:</strong> JQ 002-C2<br/><strong>Composição:</strong> 100% Algodão<br/><strong>Disponibilidade:</strong> Pronta Entrega</p>",
    productType: "Jaqueta Jeans",
    tags: ["jaqueta", "jaqueta-jeans", "pronta-entrega", "jq-002-c2"],
    images: [
      img("p37_01", "Jaqueta New Park Lazuli Clara, frente"),
      img("p37_02", "Jaqueta New Park Lazuli Clara, detalhe"),
    ],
    variants: [
      { id: "jaqueta-new-park-lazuli-clara-jq-002-c2-p", title: "P", price: "369.99", available: true, image: null },
      { id: "jaqueta-new-park-lazuli-clara-jq-002-c2-m", title: "M", price: "369.99", available: true, image: null },
      { id: "jaqueta-new-park-lazuli-clara-jq-002-c2-g", title: "G", price: "369.99", available: true, image: null },
      { id: "jaqueta-new-park-lazuli-clara-jq-002-c2-gg", title: "GG", price: "369.99", available: true, image: null },
    ],
  },
  {
    id: "jaqueta-new-park-lazuli-escura-jq-002-c2",
    title: "Jaqueta New Park Lazuli Escura",
    handle: "jaqueta-new-park-lazuli-escura-jq-002-c2",
    description: "Clássica e indispensável. Desenvolvida com tecido premium que combina leveza e resistência. O efeito estonado garante um visual autêntico e atemporal. Modelagem tradicional com caimento perfeito, gola clássica, bolsos funcionais e etiqueta exclusiva Freebong. Lavagem escura, presença marcante. Referência: JQ 002-C2. Composição: 100% Algodão. Disponibilidade: Pronta Entrega.",
    descriptionHtml: "<p>Clássica e indispensável. Desenvolvida com tecido premium que combina leveza e resistência. O efeito estonado garante um visual autêntico e atemporal. Modelagem tradicional com caimento perfeito, gola clássica, bolsos funcionais e etiqueta exclusiva Freebong. Lavagem escura, presença marcante.</p><p><strong>Referência:</strong> JQ 002-C2<br/><strong>Composição:</strong> 100% Algodão<br/><strong>Disponibilidade:</strong> Pronta Entrega</p>",
    productType: "Jaqueta Jeans",
    tags: ["jaqueta", "jaqueta-jeans", "pronta-entrega", "jq-002-c2"],
    images: [
      img("p38_01", "Jaqueta New Park Lazuli Escura, frente"),
      img("p38_03", "Jaqueta New Park Lazuli Escura, detalhe"),
    ],
    variants: [
      { id: "jaqueta-new-park-lazuli-escura-jq-002-c2-p", title: "P", price: "369.99", available: true, image: null },
      { id: "jaqueta-new-park-lazuli-escura-jq-002-c2-m", title: "M", price: "369.99", available: true, image: null },
      { id: "jaqueta-new-park-lazuli-escura-jq-002-c2-g", title: "G", price: "369.99", available: true, image: null },
      { id: "jaqueta-new-park-lazuli-escura-jq-002-c2-gg", title: "GG", price: "369.99", available: true, image: null },
    ],
  },
  {
    id: "jaqueta-up-black-jq-001-c2",
    title: "Jaqueta Up Black (JQ 001-C2)",
    handle: "jaqueta-up-black-jq-001-c2",
    description: "Jaqueta masculina desenvolvida em tecido Up Black, que oferece toque macio, conforto térmico e excelente durabilidade. Caimento moderno, proporcionando estilo e versatilidade para o dia a dia. Modelagem regular. Acabamento destroyed com efeitos de lavagem que destacam a peça. Referência: JQ 001-C2. Composição: 99% Algodão · 1% Elastano. Disponibilidade: Pronta Entrega.",
    descriptionHtml: "<p>Jaqueta masculina desenvolvida em tecido Up Black, que oferece toque macio, conforto térmico e excelente durabilidade. Caimento moderno, proporcionando estilo e versatilidade para o dia a dia. Modelagem regular. Acabamento destroyed com efeitos de lavagem que destacam a peça.</p><p><strong>Referência:</strong> JQ 001-C2<br/><strong>Composição:</strong> 99% Algodão · 1% Elastano<br/><strong>Disponibilidade:</strong> Pronta Entrega</p>",
    productType: "Jaqueta Jeans",
    tags: ["jaqueta", "jaqueta-jeans", "pronta-entrega", "jq-001-c2"],
    images: [
      img("p39_03", "Jaqueta Up Black (JQ 001-C2), frente"),
      img("p39_04", "Jaqueta Up Black (JQ 001-C2), detalhe"),
      img("p39_05", "Jaqueta Up Black (JQ 001-C2), costas"),
    ],
    variants: [
      { id: "jaqueta-up-black-jq-001-c2-p", title: "P", price: "369.99", available: true, image: null },
      { id: "jaqueta-up-black-jq-001-c2-m", title: "M", price: "369.99", available: true, image: null },
      { id: "jaqueta-up-black-jq-001-c2-g", title: "G", price: "369.99", available: true, image: null },
      { id: "jaqueta-up-black-jq-001-c2-gg", title: "GG", price: "369.99", available: true, image: null },
    ],
  },
  {
    id: "jaqueta-up-black-jq-001",
    title: "Jaqueta Up Black (JQ 001)",
    handle: "jaqueta-up-black-jq-001",
    description: "Jaqueta masculina desenvolvida em tecido Up Black, que oferece toque macio, conforto térmico e excelente durabilidade. Caimento moderno, proporcionando estilo e versatilidade para o dia a dia. Modelagem regular. Acabamento destroyed com efeitos de lavagem que destacam a peça. Referência: JQ 001. Composição: 99% Algodão · 1% Elastano. Disponibilidade: Pronta Entrega.",
    descriptionHtml: "<p>Jaqueta masculina desenvolvida em tecido Up Black, que oferece toque macio, conforto térmico e excelente durabilidade. Caimento moderno, proporcionando estilo e versatilidade para o dia a dia. Modelagem regular. Acabamento destroyed com efeitos de lavagem que destacam a peça.</p><p><strong>Referência:</strong> JQ 001<br/><strong>Composição:</strong> 99% Algodão · 1% Elastano<br/><strong>Disponibilidade:</strong> Pronta Entrega</p>",
    productType: "Jaqueta Jeans",
    tags: ["jaqueta", "jaqueta-jeans", "pronta-entrega", "jq-001"],
    images: [
      img("p40_07", "Jaqueta Up Black (JQ 001), frente"),
      img("p40_08", "Jaqueta Up Black (JQ 001), detalhe"),
    ],
    variants: [
      { id: "jaqueta-up-black-jq-001-p", title: "P", price: "369.99", available: true, image: null },
      { id: "jaqueta-up-black-jq-001-m", title: "M", price: "369.99", available: true, image: null },
      { id: "jaqueta-up-black-jq-001-g", title: "G", price: "369.99", available: true, image: null },
      { id: "jaqueta-up-black-jq-001-gg", title: "GG", price: "369.99", available: true, image: null },
    ],
  },
];
